name: Publish

on:
  release:
    types:
      - published

permissions:
  contents: write
  id-token: write

jobs:
  tag:
    name: Tag major version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - run: git push --force origin "${GITHUB_REF}:${GITHUB_REF%%.*}"
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install -g npm@latest
      - run: npm publish
