name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        required: true
      dry_run:
        type: boolean
        default: true

permissions:
  contents: write

jobs:
  release:
    name: Release ${{ inputs.version }}${{ case(inputs.dry_run, ' (dry run)', '') }}
    runs-on: ubuntu-latest
    env:
      RELEASE_REPOSITORY: ${{ github.repository }}
      RELEASE_VERSION: ${{ inputs.version }}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: package.json
      - run: npm ci
      - run: npm run release ${{ inputs.version }}
      - run: git add . && git diff --staged
      - uses: pgaskin/push-signed-commits@v1
        with:
          commit-message: Release ${{ inputs.version }}
          allow-empty: true
          dry-run: ${{ inputs.dry_run }}
        id: commit
      - uses: actions/github-script@v8
        with:
          script: |
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: context.payload.inputs.version,
              target_commitish: '${{steps.commit.outputs.pushed-oid}}',
              name: context.payload.inputs.version,
              draft: true,
            })
        if: ${{ !inputs.dry_run }}
